local opt = vim.opt
opt.termguicolors = true
opt.number = true
opt.relativenumber = true
opt.tabstop = 4
opt.softtabstop = 4
opt.shiftwidth = 4
opt.expandtab = true
opt.smartindent = true
opt.timeoutlen = 250
opt.ttimeoutlen = 0
